#!/bin/bash

brew install nodejs npm phantomjs wget

mkdir -p jscover
wget --trust-server-name --output-document=jscover/jscover.zip "http://downloads.sourceforge.net/project/jscover/JSCover-1.0.6.zip?r=http%3A%2F%2Ftntim96.github.io%2FJSCover%2F&ts=1366915691&use_mirror=hivelocity"
unzip -d jscover/jscover jscover/jscover.zip
mv jscover/jscover/target/dist/JSCover-all.jar /usr/local/lib/jscover-all.jar
rm -rf jscover

tee /usr/local/bin/jscover <<'EOF'
#!/bin/bash

java -jar /usr/local/lib/jscover-all.jar ${*:1}
EOF
chmod +x /usr/local/bin/jscover
