//= require viking/view/preamble
//
//= require viking/view/helpers
//
//= require viking/view/helpers/form_tag_helpers/tag
//= require viking/view/helpers/form_tag_helpers/content_tag
//= require viking/view/helpers/form_tag_helpers/button_tag
//= require viking/view/helpers/form_tag_helpers/check_box_tag
//= require viking/view/helpers/form_tag_helpers/text_field_tag
//= require viking/view/helpers/form_tag_helpers/hidden_field_tag
// TODO: color_field_tag
// TODO: date_field_tag
// TODO: datetime_field_tag
// TODO: datetime_local_field_tag
// TODO: email_field_tag
// TODO: field_set_tag
// TODO: file_field_tag
//= require viking/view/helpers/form_tag_helpers/form_tag
// TODO: image_submit_tag
// TODO: month_field_tag
// TODO: number_field_tag
// TODO: phone_field_tag
// TODO: range_field_tag
// TODO: search_field_tag
// TODO: telephone_field_tag
// TODO: time_field_tag
// TODO: url_field_tag
// TODO: week_field_tag
//= require viking/view/helpers/form_tag_helpers/label_tag
//= require viking/view/helpers/form_tag_helpers/options_for_select_tag
//= require viking/view/helpers/form_tag_helpers/options_from_collection_for_select_tag
//= require viking/view/helpers/form_tag_helpers/password_field_tag
//= require viking/view/helpers/form_tag_helpers/radio_button_tag
//= require viking/view/helpers/form_tag_helpers/select_tag
//= require viking/view/helpers/form_tag_helpers/submit_tag
//= require viking/view/helpers/form_tag_helpers/text_area_tag
//
// TODO: make this accept model string names
//= require viking/view/helpers/form_helpers/check_box
//= require viking/view/helpers/form_helpers/collection_select
// TODO: date_field
// TODO: date_select
// TODO: day_field
// TODO: file_field
//= require viking/view/helpers/form_helpers/form_for
//= require viking/view/helpers/form_helpers/hidden_field
//= require viking/view/helpers/form_helpers/label
// TODO: month_field
// TODO: number_field
//= require viking/view/helpers/form_helpers/password_field
// TODO: phone_field
//= require viking/view/helpers/form_helpers/radio_button
// TODO: range_field
// TODO: search_field
//= require viking/view/helpers/form_helpers/select
// TODO: telephone_field
//= require viking/view/helpers/form_helpers/text_area
//= require viking/view/helpers/form_helpers/text_field
// TODO: time_field
// TODO: url_field
// TODO: week_field
// TODO: year_field
//
//= require viking/view/form_builder
