// TODO: make this accept model string names
//= require viking/view/helpers/form_helpers/check_box
//= require viking/view/helpers/form_helpers/collection_select
// TODO: date_field
// TODO: date_select
// TODO: day_field
// TODO: file_field
//= require viking/view/helpers/form_helpers/form_for
//= require viking/view/helpers/form_helpers/hidden_field
//= require viking/view/helpers/form_helpers/label
// TODO: month_field
//= require viking/view/helpers/form_helpers/number_field
//= require viking/view/helpers/form_helpers/password_field
// TODO: phone_field
//= require viking/view/helpers/form_helpers/radio_button
// TODO: range_field
// TODO: search_field
//= require viking/view/helpers/form_helpers/select
// TODO: telephone_field
//= require viking/view/helpers/form_helpers/text_area
//= require viking/view/helpers/form_helpers/text_field
// TODO: time_field
// TODO: url_field
// TODO: week_field
// TODO: year_field