//= require viking/view/helpers/form_tag_helpers/tag
//= require viking/view/helpers/form_tag_helpers/content_tag
//= require viking/view/helpers/form_tag_helpers/button_tag
//= require viking/view/helpers/form_tag_helpers/check_box_tag
//= require viking/view/helpers/form_tag_helpers/text_field_tag
//= require viking/view/helpers/form_tag_helpers/hidden_field_tag
// TODO: date_field_tag
// TODO: datetime_field_tag
// TODO: datetime_local_field_tag
// TODO: email_field_tag
// TODO: field_set_tag
// TODO: file_field_tag
//= require viking/view/helpers/form_tag_helpers/form_tag
// TODO: image_submit_tag
// TODO: month_field_tag
//= require viking/view/helpers/form_tag_helpers/number_field_tag
//= require viking/view/helpers/form_tag_helpers/color_field_tag
// TODO: phone_field_tag
// TODO: range_field_tag
// TODO: search_field_tag
// TODO: telephone_field_tag
// TODO: time_field_tag
//= require viking/view/helpers/form_tag_helpers/time_tag
// TODO: url_field_tag
// TODO: week_field_tag
//= require viking/view/helpers/form_tag_helpers/label_tag
//= require viking/view/helpers/form_tag_helpers/options_for_select_tag
//= require viking/view/helpers/form_tag_helpers/options_from_collection_for_select_tag
//= require viking/view/helpers/form_tag_helpers/password_field_tag
//= require viking/view/helpers/form_tag_helpers/radio_button_tag
//= require viking/view/helpers/form_tag_helpers/select_tag
//= require viking/view/helpers/form_tag_helpers/submit_tag
//= require viking/view/helpers/form_tag_helpers/text_area_tag