name: CI

on:
  push:
    branches:
      - master # CI runs on pushes to master only
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
          matrix:
            node-version: [22.x, 24.x, 25.x, latest]

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm test